from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session
from typing import List

from backend.graph.workflow import research_graph
from backend.database.connection import get_db
from backend.database import crud, schemas, models
from backend.services.pdf_service import PDFService
router = APIRouter()

class ResearchRequest(BaseModel):
    query: str

    class Config:
        json_schema_extra = {
            "example": {
                "query": "What is Retrieval-Augmented Generation?"
            }
        }

class ResearchResponse(BaseModel):
    report_id: int
    report: str
    quality_score: float
    generation_time: float

@router.post("/research", response_model=ResearchResponse)
def run_research(request: ResearchRequest, db: Session = Depends(get_db)) -> ResearchResponse:
    """
    HTTP POST endpoint that invokes the LangGraph research workflow,
    persists the output in the database.
    """
    import time
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    try:
        t0 = time.time()
        # Invoke the compiled LangGraph workflow with the initial state
        initial_state = {
            "query": request.query,
            "plan": "",
            "search_results": "",
            "research": "",
            "fact_checked_research": "",
            "analysis": "",
            "citations": "",
            "report": "",
            "review_feedback": "",
            "quality_score": 0.0,
            "start_time": t0
        }
        result = research_graph.invoke(initial_state)
        generation_time = round(time.time() - t0, 2)

        # Extract workflow outputs
        report = result.get("report", "")
        quality_score = result.get("quality_score", 0.0)
        review_feedback = result.get("review_feedback", "")
        citations = result.get("citations", "")

        if not report:
            raise HTTPException(status_code=500, detail="No report was generated by the workflow.")

        # Save to database
        report_in = schemas.ReportCreate(
            query=request.query,
            report=report,
            quality_score=quality_score,
            review_feedback=review_feedback,
            citations=citations,
            generation_time=generation_time
        )
        db_report = crud.create_report(db, report=report_in)

        return ResearchResponse(
            report_id=db_report.id,
            report=db_report.report,
            quality_score=db_report.quality_score,
            generation_time=generation_time
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Workflow execution failed: {str(e)}")

@router.get("/reports", response_model=List[schemas.Report])
def get_reports(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """
    Retrieve a paginated list of all generated research reports.
    """
    return crud.get_reports(db, skip=skip, limit=limit)

@router.get("/reports/{report_id}", response_model=schemas.Report)
def get_report(report_id: int, db: Session = Depends(get_db)):
    """
    Retrieve details of a single research report by ID.
    """
    db_report = crud.get_report(db, report_id=report_id)
    if not db_report:
        raise HTTPException(status_code=404, detail="Report not found")
    return db_report

@router.delete("/reports/{report_id}")
def delete_report(report_id: int, db: Session = Depends(get_db)):
    """
    Delete a research report by ID.
    """
    success = crud.delete_report(db, report_id=report_id)
    if not success:
        raise HTTPException(status_code=404, detail="Report not found")
    return {"message": f"Report {report_id} successfully deleted"}

@router.get("/reports/{report_id}/pdf")
def export_report_pdf(report_id: int, db: Session = Depends(get_db)):
    """
    Retrieve report from SQLite and return a downloadable PDF format.
    """
    db_report = crud.get_report(db, report_id=report_id)
    if not db_report:
        raise HTTPException(status_code=404, detail="Report not found")

    try:
        pdf_buffer = PDFService.generate_report_pdf(db_report)
        filename = f"research_report_{report_id}.pdf"
        return StreamingResponse(
            pdf_buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate PDF for report {report_id}: {str(e)}"
        )
