from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from backend.graph.workflow import research_graph

router = APIRouter()

class ResearchRequest(BaseModel):
    query: str

    class Config:
        json_schema_extra = {
            "example": {
                "query": "What is Retrieval-Augmented Generation?"
            }
        }

class ResearchResponse(BaseModel):
    report: str

@router.post("/research", response_model=ResearchResponse)
def run_research(request: ResearchRequest) -> ResearchResponse:
    """
    HTTP POST endpoint that invokes the LangGraph research workflow.

    Args:
        request: The incoming request with the research query.

    Returns:
        The generated report in markdown.
    """
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    try:
        # Invoke the compiled LangGraph workflow with the initial state
        initial_state = {
            "query": request.query,
            "plan": "",
            "research": "",
            "analysis": "",
            "report": ""
        }
        result = research_graph.invoke(initial_state)

        # Extract the compiled report
        report = result.get("report", "")
        if not report:
            raise HTTPException(status_code=500, detail="No report was generated by the workflow.")

        return ResearchResponse(report=report)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Workflow execution failed: {str(e)}")
