from typing import TypedDict

class ResearchState(TypedDict):
    """
    Represents the shared state of the research assistant workflow.

    Attributes:
        query: The user's input research query.
        plan: The structured research plan generated by the Planner.
        research: The gathered research data and findings.
        analysis: The critical analysis and synthesis of findings.
        report: The final formatted markdown research report.
    """
    query: str
    plan: str
    research: str
    analysis: str
    report: str
