from typing import TypedDict

class ResearchState(TypedDict):
    """
    Represents the shared state of the research assistant workflow.

    Attributes:
        query: The user's input research query.
        plan: The structured research plan generated by the Planner.
        search_results: The gathered mock search results from web resources.
        research: The gathered research data and findings.
        fact_checked_research: The fact-checked research findings.
        analysis: The critical analysis and synthesis of findings.
        report: The final formatted markdown research report.
        review_feedback: Detailed feedback evaluating the final report's quality.
        quality_score: A quality score between 0.0 and 10.0.
    """
    query: str
    plan: str
    search_results: str
    research: str
    fact_checked_research: str
    analysis: str
    citations: str
    report: str
    review_feedback: str
    quality_score: float
